// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBvVXm0dZY0wMZGIObx_ZFrf1f2QI8MM',
    appId: '1:788118034458:web:e8e2b7fae2fbf2695519a3',
    messagingSenderId: '788118034458',
    projectId: 'gym-log-watch',
    authDomain: 'gym-log-watch.firebaseapp.com',
    storageBucket: 'gym-log-watch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleFGOP06Oy1u9mFsX_nE-4jqIUBZv7Jg',
    appId: '1:788118034458:android:ceb706ca481853c85519a3',
    messagingSenderId: '788118034458',
    projectId: 'gym-log-watch',
    storageBucket: 'gym-log-watch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDJYCzoAuSaVANJmMNYUt_nipsLpQ33U',
    appId: '1:788118034458:ios:59d530ce2a0ee4b55519a3',
    messagingSenderId: '788118034458',
    projectId: 'gym-log-watch',
    storageBucket: 'gym-log-watch.firebasestorage.app',
    iosBundleId: 'com.gymlog',
  );
}
